### ISSUE TITLE
Errore caricamento slide

### ISSUE THREAD

**Issue by kocierik** [csunibo/ingegneria-del-software#2]
La slide relative al progetto non caricano https://csunibo.github.io/ingegneria-del-software/lucidi/project/

**Comment by lucat1** [comment]
(una vera tragedia, e' un corso cosi' emozionante)

Comunque confermo neanche a me e segna "invalid pdf structure" in console.
Bisogna ripescarle e ricaricarle. Se vuoi puoi fare tu, altrimenti faccio io

Cito anche @FoxySeta che li ha caricati in origine.

**Comment by kocierik** [comment]
@FoxySeta inaccettabile...

**Comment by foxyseta** [comment]
Ne ero già a conoscenza. Anche qualcosina su https://csunibo.github.io/basi-di-dati.
@kocierik quali sono esattamente i nomi di questi pacchi di lucidi?

**Comment by lucat1** [comment]
Ah tutti i file in quella cartella non vanno, ho controllato

**Comment by kocierik** [comment]
fixato @FoxySeta @lucat1 [👍](https://emojipedia.org/thumbs-up/)

**Comment by foxyseta** [comment]
Bravissimo, grazie. Hai controllato anche basi di dati?

**Comment by kocierik** [comment]
al momento no, ci guarderò!
